name: Test the environment build
on: 
  push:
    paths:
      - environment.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  build-env:
    name: conda build
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: example-env
      - run: conda list
      - run: python -c "import rioxarray"
      - run: python -c "import geopandas"
